packageExtensions:
  "@mui/core@*":
    dependencies:
      "@mui/system": "^5.0.6"
  "@mui/styled-engine@*":
    dependencies:
      "@emotion/styled": "^11.3.0"
  argon2@*:
    dependencies:
      node-gyp: ^8.4.0
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.16.0
  relay-compiler@*:
    dependencies:
      relay-compiler-language-typescript: ^14.3.0
      relay-config: ^12.0.0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-bundle.cjs
    spec: "https://yarnplugins.com/bundle"
  - path: .yarn/plugins/@yarnpkg/plugin-push.cjs
    spec: "https://yarnplugins.com/push"

yarnPath: .yarn/releases/yarn-3.2.0-rc.2.cjs
